[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_pgsql", "php83Extensions.pgsql"]

[phases.install]
cmds = ["cd backend && composer install --no-dev"]

[start]
cmd = "cd backend && php -S 0.0.0.0:$PORT -t public"
